apiVersion: v1
kind: Pod
metadata:
  name: mavenwebpp
  labels:
    app: mavenwebapp
spec:
  containers:
    - name: mavenwebapp
      image: vijaysvk333/mavenwebapp_dockerhub:v1.$BUILD_ID
      ports:
        - containerPort: 8080
